---

sudo: required

services:
  - docker

install:
  - docker pull hadolint/hadolint
  - docker build -t test/test .

script:
  - docker run --rm -i hadolint/hadolint < Dockerfile
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test terraform version
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test tflint -v
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test cred-alert version
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test detect-secrets --version
