---

sudo: required

services:
  - docker

install:
  - docker build -t test/test .

script:
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test terraform version
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test terraform tflint -v
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test terraform cred-alert version
  - docker run --rm -v $(pwd):/work/ --workdir=/work/ -t test/test terraform detect-secrets --version
